/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Grocery as PrismaGrocery } from "@prisma/client";

export class GroceryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.GroceryCountArgs, "select">): Promise<number> {
    return this.prisma.grocery.count(args);
  }

  async groceries(args: Prisma.GroceryFindManyArgs): Promise<PrismaGrocery[]> {
    return this.prisma.grocery.findMany(args);
  }
  async grocery(
    args: Prisma.GroceryFindUniqueArgs
  ): Promise<PrismaGrocery | null> {
    return this.prisma.grocery.findUnique(args);
  }
  async createGrocery(args: Prisma.GroceryCreateArgs): Promise<PrismaGrocery> {
    return this.prisma.grocery.create(args);
  }
  async updateGrocery(args: Prisma.GroceryUpdateArgs): Promise<PrismaGrocery> {
    return this.prisma.grocery.update(args);
  }
  async deleteGrocery(args: Prisma.GroceryDeleteArgs): Promise<PrismaGrocery> {
    return this.prisma.grocery.delete(args);
  }
}
